version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "23:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 3
